use crate::config::{self, Mode};
use crate::instrument_detect::body_is_instrumented;
use clippy_utils::diagnostics::span_lint_hir_and_then;
use rustc_hir::def_id::{CRATE_DEF_ID, LocalDefId};
use rustc_hir::intravisit::FnKind;
use rustc_hir::{Body, CRATE_HIR_ID, FnDecl, HirId};
use rustc_lint::{LateContext, LateLintPass};
use rustc_middle::lint::LintLevelSource;
use rustc_session::lint::Level;
use rustc_session::{declare_lint, impl_lint_pass};
use rustc_span::{Span, Symbol};

declare_lint! {
    /// ### What it does
    ///
    /// Checks for functions that are not instrumented with
    /// `#[tracing::instrument]`. Every free function, inherent method,
    /// trait-impl method and trait default method with a body is in scope;
    /// `const fn`s, closures and anything compiled under `--test` are not.
    ///
    /// ### Why is this bad?
    ///
    /// A function without a span is invisible in a trace: its time is
    /// attributed to whichever caller happens to be instrumented, and its
    /// arguments are never recorded. Requiring the attribute everywhere makes
    /// trace coverage the default rather than something someone remembered.
    ///
    /// ### Example
    ///
    /// ```rust,ignore
    /// pub fn load(path: &Path) -> io::Result<Config> {
    ///     // ...
    /// }
    /// ```
    ///
    /// Use instead:
    ///
    /// ```rust,ignore
    /// #[tracing::instrument]
    /// pub fn load(path: &Path) -> io::Result<Config> {
    ///     // ...
    /// }
    /// ```
    pub UNINSTRUMENTED_FN,
    Deny,
    "function is not instrumented with `#[tracing::instrument]`"
    // Deliberately *not* `report_in_external_macro`. A function generated by
    // another crate's macro has no source line where a consumer could write
    // `#[instrument]`, and builtin derives (`Debug`, `Clone`, ...) would fire on
    // every derived method. rustc cancels those diagnostics for us.
}

declare_lint! {
    /// ### What it does
    ///
    /// Checks for `allow(uninstrumented_fn)` or `expect(uninstrumented_fn)`
    /// that carries no `reason = "..."`, and for a `dylint.toml` that switches
    /// `hyp_tracing` off without one. An `expect` is checked because it is an
    /// exemption too: once fulfilled, it silences the function indefinitely.
    ///
    /// ### Why is this bad?
    ///
    /// Leaving a function out of the trace should be a deliberate, explained
    /// decision. A written reason makes whoever adds the exemption say why,
    /// and leaves that argument in the code for the next reader.
    ///
    /// ### Example
    ///
    /// ```rust,ignore
    /// #[allow(uninstrumented_fn)]
    /// fn decode_byte(b: u8) -> u8 { b ^ 0x5a }
    /// ```
    ///
    /// Use instead:
    ///
    /// ```rust,ignore
    /// #[allow(uninstrumented_fn, reason = "called per byte in the decoder hot loop")]
    /// fn decode_byte(b: u8) -> u8 { b ^ 0x5a }
    /// ```
    pub INSTRUMENT_EXEMPTION_WITHOUT_JUSTIFICATION,
    Deny,
    "`allow` or `expect` of `uninstrumented_fn`, or a `dylint.toml` opt-out, without a stated reason",
    // The span may be an `allow` attribute that a consumer's macro wrote.
    // Without this, rustc would cancel the diagnostic before it is rendered,
    // and the justification requirement would be unenforceable there.
    report_in_external_macro
}

#[derive(Default)]
pub struct TracingFns {
    /// Whether `check_fn` reports anything for the crate being compiled.
    /// Decided once, in `check_crate`.
    enforce: bool,
}

impl_lint_pass!(TracingFns => [UNINSTRUMENTED_FN, INSTRUMENT_EXEMPTION_WITHOUT_JUSTIFICATION]);

impl<'tcx> LateLintPass<'tcx> for TracingFns {
    fn check_crate(&mut self, cx: &LateContext<'tcx>) {
        self.enforce = false;

        // A `--test` compilation is test code: `#[test]` functions,
        // `#[cfg(test)]` helpers, integration-test crates. None of it needs a
        // span. Production code is still checked, in the ordinary lib/bin
        // compilation that `--all-targets` also performs -- and in the one a
        // run *without* `--all-targets` performs, so unlike `hyp_hegel` this
        // library does not depend on that flag.
        if cx.tcx.sess.opts.test {
            return;
        }

        let config = match config::load() {
            Ok(config) => config,
            Err(error) => {
                // Neither "enforce" nor "off" is a safe guess for a switch
                // nobody can read: the build fails and says why. The toml
                // error's `Display` ends in a whitespace-only line; trimmed.
                cx.tcx.dcx().err(format!(
                    "could not read `[{}]` from `dylint.toml`: {}",
                    config::TABLE,
                    error.to_string().trim_end()
                ));
                return;
            }
        };

        match config.mode() {
            Mode::Enforce => self.enforce = true,
            Mode::Off => {}
            // Reported once, at the crate root (the span
            // `crate_without_hegel_tests` uses), and `uninstrumented_fn` stays
            // off: the configuration is what needs fixing, and an error per
            // function would bury it.
            Mode::OffWithoutReason => {
                let crate_span = cx.tcx.def_span(CRATE_DEF_ID);
                let span = cx.tcx.sess.source_map().start_point(crate_span);
                span_lint_hir_and_then(
                    cx,
                    INSTRUMENT_EXEMPTION_WITHOUT_JUSTIFICATION,
                    CRATE_HIR_ID,
                    span,
                    "`hyp_tracing` is disabled in `dylint.toml` without a stated reason",
                    |diag| {
                        diag.help(
                            "add `reason = \"...\"` under `[hyp_tracing]` explaining why this workspace does not instrument its functions",
                        );
                    },
                );
            }
        }
    }

    fn check_fn(
        &mut self,
        cx: &LateContext<'tcx>,
        kind: FnKind<'tcx>,
        _decl: &'tcx FnDecl<'_>,
        body: &'tcx Body<'_>,
        _span: Span,
        def_id: LocalDefId,
    ) {
        if !self.enforce {
            return;
        }

        // Closures are not something a consumer can annotate, and a `const fn`
        // cannot take `#[instrument]` at all. An `async fn` arrives here twice
        // -- as the function (`ItemFn`/`Method`) and as its coroutine
        // (`Closure`) -- and only the first is checked.
        if matches!(kind, FnKind::Closure) || cx.tcx.is_const_fn(def_id.to_def_id()) {
            return;
        }

        // Re-fetched through `tcx` for the `'tcx` lifetime on the `Body`'s
        // contents, which `body_is_instrumented`'s visitor needs.
        if body_is_instrumented(cx, cx.tcx.hir_body(body.id())) {
            return;
        }

        let hir_id = cx.tcx.local_def_id_to_hir_id(def_id);

        // An `allow` suppresses `uninstrumented_fn` by construction, so the
        // justified and unjustified cases are indistinguishable from the
        // emission path alone -- the level has to be inspected directly. Same
        // table as `hyp_hegel`'s `non_hegel_test`; see `hegel_tests.rs` for the
        // API notes on `lint_level_spec_at_node`.
        //
        // An `expect` is an exemption too: once `uninstrumented_fn` is emitted
        // and fulfils it, the function is silenced for as long as the attribute
        // stays. So it needs a reason exactly as an `allow` does.
        //
        // Capped levels (`--cap-lints`, which cargo passes for dependencies)
        // are deliberately not special-cased. A `Default` level capped to
        // `allow` lands in the `(Level::Allow, _)` arm, and a capped
        // `deny`/`warn` attribute can reach a `Node` arm -- where the
        // justification diagnostic is itself capped and never shown. Both are
        // harmless; do not "fix" these arms for them.
        let spec = cx.tcx.lint_level_spec_at_node(UNINSTRUMENTED_FN, hir_id);

        match (spec.level(), spec.src) {
            // Exempted in source with a stated reason: accepted.
            (Level::Allow, LintLevelSource::Node { reason, .. }) if has_reason(reason) => {}

            // Exempted in source with no reason, or a blank one: report the
            // attribute. `span` covers just the lint name inside it.
            (
                Level::Allow,
                LintLevelSource::Node {
                    span: attr_span, ..
                },
            ) => emit_unjustified(cx, hir_id, attr_span, "allow"),

            // Expected in source with no reason, or a blank one: report the
            // attribute, *and* emit `uninstrumented_fn` so the expectation is
            // still fulfilled -- otherwise rustc would add an
            // unfulfilled-expectation warning on top of the real problem. A
            // justified `expect` falls through to the last arm.
            (
                Level::Expect,
                LintLevelSource::Node {
                    reason,
                    span: attr_span,
                    ..
                },
            ) if !has_reason(reason) => {
                emit_unjustified(cx, hir_id, attr_span, "expect");
                emit_uninstrumented(cx, hir_id, def_id);
            }

            // Allowed from the command line (`-A uninstrumented_fn`): a
            // deliberate operator decision, not a source-level exemption.
            (Level::Allow, _) => {}

            // Everything else -- the `Deny` default, an explicit `warn` or
            // `deny`, or an `expect` from the command line -- is emitted at the
            // function's own `HirId`, so rustc resolves the level against the
            // function and its parents, not against whichever node the pass is
            // visiting.
            _ => emit_uninstrumented(cx, hir_id, def_id),
        }
    }
}

/// Whether an `allow`/`expect` attribute states a reason. Only the *presence*
/// of a non-blank reason is checked, never its quality; why `reason = "n/a"`
/// passes and only blank reasons fail: see the same arm in
/// `hyp_hegel/src/hegel_tests.rs`.
fn has_reason(reason: Option<Symbol>) -> bool {
    reason.is_some_and(|reason| !reason.as_str().trim().is_empty())
}

/// Report `UNINSTRUMENTED_FN` at the function's own `HirId`, so rustc resolves
/// its level (and fulfils any `expect`) against the function and its parents.
fn emit_uninstrumented(cx: &LateContext<'_>, hir_id: HirId, def_id: LocalDefId) {
    span_lint_hir_and_then(
        cx,
        UNINSTRUMENTED_FN,
        hir_id,
        cx.tcx.def_span(def_id),
        "function is not instrumented with `#[tracing::instrument]`",
        |diag| {
            diag.help(
                "add `#[tracing::instrument]`, or exempt it with `allow(uninstrumented_fn, reason = \"...\")`",
            );
        },
    );
}

/// Report an `allow`/`expect` of `uninstrumented_fn` that has no reason, at the
/// attribute's lint-name span. `attr` is the attribute's name, for the message.
fn emit_unjustified(cx: &LateContext<'_>, hir_id: HirId, attr_span: Span, attr: &str) {
    span_lint_hir_and_then(
        cx,
        INSTRUMENT_EXEMPTION_WITHOUT_JUSTIFICATION,
        hir_id,
        attr_span,
        format!("`{attr}(uninstrumented_fn)` without a stated reason"),
        |diag| {
            diag.help("add `reason = \"...\"` explaining why this function is not instrumented");
        },
    );
}
