use crate::instrument_detect::body_is_instrumented;
use clippy_utils::diagnostics::span_lint_hir_and_then;
use rustc_hir::def_id::LocalDefId;
use rustc_hir::intravisit::FnKind;
use rustc_hir::{Body, FnDecl};
use rustc_lint::{LateContext, LateLintPass};
use rustc_middle::lint::LintLevelSource;
use rustc_session::lint::Level;
use rustc_session::{declare_lint, impl_lint_pass};
use rustc_span::Span;

declare_lint! {
    /// ### What it does
    ///
    /// Checks for functions that are not instrumented with
    /// `#[tracing::instrument]`. Every free function, inherent method,
    /// trait-impl method and trait default method with a body is in scope;
    /// `const fn`s, closures and anything compiled under `--test` are not.
    ///
    /// ### Why is this bad?
    ///
    /// A function without a span is invisible in a trace: its time is
    /// attributed to whichever caller happens to be instrumented, and its
    /// arguments are never recorded. Requiring the attribute everywhere makes
    /// trace coverage the default rather than something someone remembered.
    ///
    /// ### Example
    ///
    /// ```rust,ignore
    /// pub fn load(path: &Path) -> io::Result<Config> {
    ///     // ...
    /// }
    /// ```
    ///
    /// Use instead:
    ///
    /// ```rust,ignore
    /// #[tracing::instrument]
    /// pub fn load(path: &Path) -> io::Result<Config> {
    ///     // ...
    /// }
    /// ```
    pub UNINSTRUMENTED_FN,
    Deny,
    "function is not instrumented with `#[tracing::instrument]`"
    // Deliberately *not* `report_in_external_macro`. A function generated by
    // another crate's macro has no source line where a consumer could write
    // `#[instrument]`, and builtin derives (`Debug`, `Clone`, ...) would fire on
    // every derived method. rustc cancels those diagnostics for us.
}

declare_lint! {
    /// ### What it does
    ///
    /// Checks for `allow(uninstrumented_fn)` that carries no
    /// `reason = "..."`, and for a `dylint.toml` that switches `hyp_tracing`
    /// off without one.
    ///
    /// ### Why is this bad?
    ///
    /// Leaving a function out of the trace should be a deliberate, explained
    /// decision. A written reason makes whoever adds the exemption say why,
    /// and leaves that argument in the code for the next reader.
    ///
    /// ### Example
    ///
    /// ```rust,ignore
    /// #[allow(uninstrumented_fn)]
    /// fn decode_byte(b: u8) -> u8 { b ^ 0x5a }
    /// ```
    ///
    /// Use instead:
    ///
    /// ```rust,ignore
    /// #[allow(uninstrumented_fn, reason = "called per byte in the decoder hot loop")]
    /// fn decode_byte(b: u8) -> u8 { b ^ 0x5a }
    /// ```
    pub INSTRUMENT_EXEMPTION_WITHOUT_JUSTIFICATION,
    Deny,
    "`allow(uninstrumented_fn)` or a `dylint.toml` opt-out without a stated reason",
    // The span may be an `allow` attribute that a consumer's macro wrote.
    // Without this, rustc would cancel the diagnostic before it is rendered,
    // and the justification requirement would be unenforceable there.
    report_in_external_macro
}

#[derive(Default)]
pub struct TracingFns;

impl_lint_pass!(TracingFns => [UNINSTRUMENTED_FN, INSTRUMENT_EXEMPTION_WITHOUT_JUSTIFICATION]);

impl<'tcx> LateLintPass<'tcx> for TracingFns {
    fn check_fn(
        &mut self,
        cx: &LateContext<'tcx>,
        kind: FnKind<'tcx>,
        _decl: &'tcx FnDecl<'_>,
        body: &'tcx Body<'_>,
        _span: Span,
        def_id: LocalDefId,
    ) {
        // Closures are not something a consumer can annotate, and a `const fn`
        // cannot take `#[instrument]` at all. An `async fn` arrives here twice
        // -- as the function (`ItemFn`/`Method`) and as its coroutine
        // (`Closure`) -- and only the first is checked.
        if matches!(kind, FnKind::Closure) || cx.tcx.is_const_fn(def_id.to_def_id()) {
            return;
        }

        // Re-fetched through `tcx` for the `'tcx` lifetime on the `Body`'s
        // contents, which `body_is_instrumented`'s visitor needs.
        if body_is_instrumented(cx, cx.tcx.hir_body(body.id())) {
            return;
        }

        let hir_id = cx.tcx.local_def_id_to_hir_id(def_id);

        // An `allow` suppresses `uninstrumented_fn` by construction, so the
        // justified and unjustified cases are indistinguishable from the
        // emission path alone -- the level has to be inspected directly. Same
        // table as `hyp_hegel`'s `non_hegel_test`; see `hegel_tests.rs` for the
        // API notes on `lint_level_spec_at_node`.
        let spec = cx.tcx.lint_level_spec_at_node(UNINSTRUMENTED_FN, hir_id);

        match (spec.level(), spec.src) {
            // Exempted in source with a stated reason: accepted. Only the
            // *presence* of a non-blank reason is checked, never its quality.
            (
                Level::Allow,
                LintLevelSource::Node {
                    reason: Some(reason),
                    ..
                },
            ) if !reason.as_str().trim().is_empty() => {}

            // Exempted in source with no reason, or a blank one: report the
            // attribute. `span` covers just the lint name inside it.
            (
                Level::Allow,
                LintLevelSource::Node {
                    span: attr_span, ..
                },
            ) => {
                span_lint_hir_and_then(
                    cx,
                    INSTRUMENT_EXEMPTION_WITHOUT_JUSTIFICATION,
                    hir_id,
                    attr_span,
                    "`allow(uninstrumented_fn)` without a stated reason",
                    |diag| {
                        diag.help(
                            "add `reason = \"...\"` explaining why this function is not instrumented",
                        );
                    },
                );
            }

            // Allowed from the command line (`-A uninstrumented_fn`): a
            // deliberate operator decision, not a source-level exemption.
            (Level::Allow, _) => {}

            // Everything else -- the `Deny` default, or an explicit `warn`,
            // `deny` or `expect` -- is emitted at the function's own `HirId`,
            // so rustc resolves the level against the function and its
            // parents, not against whichever node the pass is visiting.
            _ => {
                span_lint_hir_and_then(
                    cx,
                    UNINSTRUMENTED_FN,
                    hir_id,
                    cx.tcx.def_span(def_id),
                    "function is not instrumented with `#[tracing::instrument]`",
                    |diag| {
                        diag.help(
                            "add `#[tracing::instrument]`, or exempt it with `allow(uninstrumented_fn, reason = \"...\")`",
                        );
                    },
                );
            }
        }
    }
}
