use crate::hegel_detect::{body_calls_hegel, expansion_chain_includes_hegel};
use crate::test_fns::find_test_fns;
use clippy_utils::diagnostics::span_lint_and_help;
use rustc_data_structures::fx::FxHashSet;
use rustc_hir::Item;
use rustc_hir::def_id::DefId;
use rustc_lint::{LateContext, LateLintPass};
use rustc_middle::lint::LintLevelSource;
use rustc_session::lint::Level;
use rustc_session::{declare_lint, impl_lint_pass};

declare_lint! {
    /// ### What it does
    ///
    /// Checks for test functions that do not use the hegel property-testing
    /// framework. For this lint to be effective, `--all-targets` must be passed
    /// to `cargo dylint`.
    ///
    /// ### Why is this bad?
    ///
    /// Example-based tests only exercise the cases someone thought to write.
    /// Property-based tests explore combinations and boundary conditions that
    /// humans do not think of, and shrink failures to minimal counterexamples.
    ///
    /// ### Example
    ///
    /// ```rust,ignore
    /// #[test]
    /// fn addition_works() {
    ///     assert_eq!(2 + 2, 4);
    /// }
    /// ```
    ///
    /// Use instead:
    ///
    /// ```rust,ignore
    /// #[hegel::test]
    /// fn addition_commutes(tc: hegel::TestCase) {
    ///     let a = tc.draw(hegel::generators::integers::<i64>());
    ///     let b = tc.draw(hegel::generators::integers::<i64>());
    ///     assert_eq!(a.wrapping_add(b), b.wrapping_add(a));
    /// }
    /// ```
    pub NON_HEGEL_TEST,
    Deny,
    "test does not use the hegel property-testing framework",
    // A test generated by an attribute macro from another crate — `#[hegel::test]`
    // itself, but equally `#[tokio::test]` or `#[rstest]` — has a span inside that
    // macro's expansion. rustc silently cancels such a diagnostic unless the lint
    // opts in here (`rustc_middle::lint::lint_level`), so without this the policy
    // would be unenforceable against exactly the tests it most needs to reach, and
    // the `hegel_test.rs` fixture would pass for the wrong reason.
    report_in_external_macro
}

declare_lint! {
    /// ### What it does
    ///
    /// Checks for `allow(non_hegel_test)` that carries no `reason = "..."`.
    ///
    /// ### Why is this bad?
    ///
    /// Silencing the property-testing requirement should be a deliberate,
    /// explained decision. Requiring a written reason forces whoever adds the
    /// exemption — human or agent — to articulate why a property test does not
    /// apply, and leaves that argument in the code for the next reader.
    ///
    /// ### Example
    ///
    /// ```rust,ignore
    /// #[allow(non_hegel_test)]
    /// #[test]
    /// fn golden_wire_format() {}
    /// ```
    ///
    /// Use instead:
    ///
    /// ```rust,ignore
    /// #[allow(non_hegel_test, reason = "asserts an exact byte layout; no general property holds")]
    /// #[test]
    /// fn golden_wire_format() {}
    /// ```
    pub HEGEL_EXEMPTION_WITHOUT_JUSTIFICATION,
    Deny,
    "`allow(non_hegel_test)` without a stated reason",
    // The span this lint reports is the `allow` attribute's lint-name span. A
    // consumer can generate that attribute from a macro — a `#[test]`-emitting
    // macro that also writes the exemption, say — and rustc would then cancel
    // the diagnostic before it is ever rendered. Opting in here keeps the
    // justification requirement enforceable wherever the exemption is written.
    report_in_external_macro
}

declare_lint! {
    /// ### What it does
    ///
    /// Checks for crates that have a test harness but contain no hegel
    /// property tests at all.
    ///
    /// ### Why is this bad?
    ///
    /// A crate that has opted into testing but uses no property testing is
    /// missing the primary constraint this policy exists to enforce. A crate
    /// with no tests at all is a separate concern and is not reported here.
    ///
    /// ### Interaction with `allow(non_hegel_test)`
    ///
    /// A crate whose tests are *all* individually exempted — even with a
    /// justified `allow(non_hegel_test)` on every one — is still reported.
    /// An exemption from the per-test rule is not an exemption from this one.
    /// That is deliberate: it keeps "this crate does no property testing"
    /// visible as a single fact, rather than letting it accumulate one
    /// justified exemption at a time until nobody notices. A crate that has
    /// genuinely decided against property testing silences this lint
    /// explicitly, with a crate-level
    /// `#![allow(crate_without_hegel_tests, reason = "...")]`.
    ///
    /// ### Example
    ///
    /// ```rust,ignore
    /// #[test]
    /// fn one() {}
    /// #[test]
    /// fn two() {}
    /// ```
    ///
    /// Use instead:
    ///
    /// ```rust,ignore
    /// #[hegel::test]
    /// fn property(tc: hegel::TestCase) {}
    /// ```
    pub CRATE_WITHOUT_HEGEL_TESTS,
    Deny,
    "crate has tests but no hegel property tests"
    // Deliberately *not* `report_in_external_macro`, unlike the two lints
    // above. Their spans are a test function or an `allow` attribute, either
    // of which a macro can generate; this lint's span is the first character
    // of the crate root file, whose `SyntaxContext` is the root context by
    // construction, so the flag could never change whether the diagnostic
    // survives. Verified: the lint fires without it. If the span is ever
    // moved off the crate root — onto an offending test, say — add the flag.
}

#[derive(Default)]
pub struct HegelTests {
    test_fns: FxHashSet<DefId>,
    /// Tests recognised as hegel tests, counted as `check_item` visits them.
    /// Read by `check_crate_post` to decide whether `CRATE_WITHOUT_HEGEL_TESTS`
    /// fires.
    hegel_test_count: usize,
}

impl_lint_pass!(HegelTests => [
    NON_HEGEL_TEST,
    HEGEL_EXEMPTION_WITHOUT_JUSTIFICATION,
    CRATE_WITHOUT_HEGEL_TESTS
]);

impl<'tcx> LateLintPass<'tcx> for HegelTests {
    /// Collect the crate's test functions. Nothing is reported from here.
    ///
    /// Recovering a `#[test]` function requires scanning every free item in
    /// the crate for the harness-generated `TestDescAndFn` constant that
    /// refers to it, so the collection genuinely needs a whole-crate pass. The
    /// reporting deliberately does not: see `check_item`.
    fn check_crate(&mut self, cx: &LateContext<'tcx>) {
        // Reset before collecting, so the pass is idempotent if rustc ever
        // reuses one instance across crates. `test_fns` is overwritten
        // wholesale below, but `hegel_test_count` only ever increments, and a
        // stale non-zero count would silently suppress
        // `CRATE_WITHOUT_HEGEL_TESTS` on the next crate — a false negative
        // with no symptom. One line here is cheaper than depending on rustc's
        // instantiation policy staying as it is.
        self.hegel_test_count = 0;
        self.test_fns = find_test_fns(cx);
    }

    /// Report on a test function while it is the item being visited.
    ///
    /// Diagnostics are emitted here rather than from `check_crate` because
    /// `LateContext` resolves a lint's level against
    /// `last_node_with_lint_attrs`, which is only the item's own `HirId` while
    /// that item is being visited. During `check_crate` it is still
    /// `CRATE_HIR_ID`, so every `#[warn]`, `#[deny]`, `#[expect]` and
    /// `#[allow]` written on a test or its enclosing module was silently
    /// ignored and the lint always fired at its declared default level.
    fn check_item(&mut self, cx: &LateContext<'tcx>, item: &'tcx Item<'tcx>) {
        let def_id = item.owner_id.to_def_id();
        if !self.test_fns.contains(&def_id) {
            return;
        }

        let span = cx.tcx.def_span(def_id);
        // `#[hegel::test]` shows up in the expansion chain; the builder
        // form is a plain `#[test]` and only shows up in the body.
        let is_hegel = expansion_chain_includes_hegel(cx, span)
            || def_id
                .as_local()
                .is_some_and(|local| body_calls_hegel(cx, local));
        if is_hegel {
            self.hegel_test_count += 1;
            return;
        }

        // An `allow` suppresses `non_hegel_test` by construction, so the
        // justified and unjustified cases are indistinguishable from the
        // emission path alone — the level has to be inspected directly.
        //
        // `lint_level_spec_at_node` returns `StableLevelSpec`, whose `level`
        // field is deliberately private — read it through `.level()`. `src`
        // is public and destructures directly. Verified against this
        // nightly's `rustc_middle::lint` in the Task 2 spike; do not
        // substitute `lint_level_at_node`, which does not exist here.
        let spec = cx
            .tcx
            .lint_level_spec_at_node(NON_HEGEL_TEST, item.hir_id());

        match (spec.level(), spec.src) {
            // Exempted in source with a stated reason: accepted.
            //
            // Only the *presence* of a non-empty reason is checked, never its
            // quality: `reason = "n/a"` passes. That boundary is deliberate —
            // judging whether an explanation is a real justification is not
            // something a lint can do, and pretending otherwise would mean
            // failing builds over prose. The empty and whitespace-only cases
            // are excluded because they are the one degenerate form that is
            // mechanically detectable, and `reason = ""` plainly satisfies the
            // letter of the policy while defeating its entire purpose.
            (
                Level::Allow,
                LintLevelSource::Node {
                    reason: Some(reason),
                    ..
                },
            ) if !reason.as_str().trim().is_empty() => {}

            // Exempted in source with no reason, or an empty one: report the
            // attribute.
            // `span` covers just the lint name inside the attribute, not
            // the whole `#[allow(...)]`.
            (
                Level::Allow,
                LintLevelSource::Node {
                    span: attr_span, ..
                },
            ) => {
                span_lint_and_help(
                    cx,
                    HEGEL_EXEMPTION_WITHOUT_JUSTIFICATION,
                    attr_span,
                    "`allow(non_hegel_test)` without a stated reason",
                    None,
                    "add `reason = \"...\"` explaining why a property test does not apply here",
                );
            }

            // Allowed from the command line (`-A non_hegel_test`): a
            // deliberate operator decision, not a source-level exemption.
            (Level::Allow, _) => {}

            // Every other level — the `Deny` default, or an explicit
            // `#[warn]` / `#[deny]` / `#[expect]` — is left to rustc, which
            // now resolves it against this item.
            _ => {
                span_lint_and_help(
                    cx,
                    NON_HEGEL_TEST,
                    span,
                    "test does not use the hegel property-testing framework",
                    None,
                    "rewrite this as a property test using `#[hegel::test]`",
                );
            }
        }
    }

    /// Report a crate that runs tests but none of them are hegel tests.
    ///
    /// Runs once, after every item has been visited, so `hegel_test_count` is
    /// final by the time it is read.
    fn check_crate_post(&mut self, cx: &LateContext<'tcx>) {
        // A crate with no test harness at all stays silent: "this crate has no
        // tests" is a different policy question and deliberately out of scope
        // here. Only a crate that has opted into testing and then used no
        // property testing is reported.
        if self.test_fns.is_empty() || self.hegel_test_count > 0 {
            return;
        }

        let crate_span = cx.tcx.def_span(rustc_hir::def_id::CRATE_DEF_ID);
        let span = cx.tcx.sess.source_map().start_point(crate_span);
        span_lint_and_help(
            cx,
            CRATE_WITHOUT_HEGEL_TESTS,
            span,
            "crate has tests but no hegel property tests",
            None,
            "add at least one `#[hegel::test]` property test to this crate",
        );
    }
}
